version: '3.8'

services:
  pobo-sdk-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pobo-sdk-php
    volumes:
      - .:/var/www

  pobo-sdk-nginx:
    image: nginx:alpine
    container_name: pobo-sdk-nginx
    ports:
      - "6020:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pobo-sdk-php